### ISSUE TITLE
Consider moving to WIFIMANAGER

### ISSUE THREAD

**Issue by stuartpittaway** [stuartpittaway/diyBMSv4Code#1]
WIFIMANAGER is external library and removes need to roll own WIFI configuration pages

**Comment by stuartpittaway** [comment]
This isn't required, WIFIMANAGER doesn't support ESP32

**Comment by ortegafernando** [comment]
Hi, wifimanager has a developement branch and has support for esp32 since more than 1 year ago (it has been already "checked"), please consider it, thanks. (if you like it)
