### ISSUE TITLE
No connection after fw update

### ISSUE THREAD

**Issue by jency001** [stuartpittaway/diyBMSv4Code#112]
Hi Stuart,

I wanted to update the esp8266 module because I wanted it to connect to another network. So I reinstalled the latest fw but the esp does not find any modules. Is is because the fw on the board is older than that of the esp?

Kind regards

**Comment by stuartpittaway** [comment]
It should work, is there a red message bar saying Found X modules?

**Comment by jency001** [comment]
![image](https://user-images.githubusercontent.com/25853633/120931879-be7abf00-c6f3-11eb-80da-835c172f8ef4.png)
i ngot tx to rx connected and vise versa. it did work befor and now i am trying to get one working but no connection also no green leds blinking

**Comment by stuartpittaway** [comment]
Ok, connect tx to Rx on the controller only, no modules. Do you get an error count number  increase?

**Comment by jency001** [comment]
yes i do

**Comment by jency001** [comment]
also intressting when i plug in rx on the module from tx from the controller the blue led stops blinking no leds are blinking now. en wehn i remove the cable te led blenks every 10 sec

**Comment by stuartpittaway** [comment]
How old is the firmware on the modules?

**Comment by jency001** [comment]
more than 1 year

**Comment by stuartpittaway** [comment]
Ok, it's likely very old compared to the controller. So you would need to flash the modules as well
