### ISSUE TITLE
MQTT: cell 8 not sending any messages

### ISSUE THREAD

**Issue by SKOJau** [stuartpittaway/diyBMSv4Code#116]
Somehow i don't get any MQTT messages from my 8th cell.

Version: 6c3d59e04910a67302dc542fed006e4628ca6fa7
Compiled: 2021-06-16T12:09:39.012Z

![grafik](https://user-images.githubusercontent.com/44570259/123875547-2fe80f00-d93a-11eb-82ac-f98547213d37.png)

**Comment by manuromero05** [comment]
same problem same, same cell.

Release-2021-07-06-10-47

**Comment by SKOJau** [comment]
Moved to : https://github.com/stuartpittaway/diyBMSv4ESP32/issues/36
Problem is with the ESP32 Code
