### ISSUE TITLE
Last module in second bank has invalid voltage

### ISSUE THREAD

**Issue by hotear** [stuartpittaway/diyBMSv4Code#21]
I’ve just finished connecting my second 14s to the controller and assigned each to the second bank (bank 1) and for some reason the last cell on the second bank has invalid voltage. I’ve substituted a different module for that cell and it also has the same issue. If I assign that module back to the first bank (bank 0) it reads a voltage correctly. I therefore think the issue is in the controller code rather than with the module.

**Comment by stuartpittaway** [comment]
How bizarre.  If you move the bad module to another slot in bank 1 does it still read incorrectly?

**Comment by stuartpittaway** [comment]
Fixed by pull request
