### ISSUE TITLE
Compile message SPIFFS has been deprecated. Please consider moving to LittleFS

### ISSUE THREAD

**Issue by stuartpittaway** [stuartpittaway/diyBMSv4Code#28]
SPIFFS has been deprecated. Please consider moving to LittleFS or other filesystems. [-Wdeprecated-declarations]

When compiling controller code

**Comment by daromer2** [comment]
@stuartpittaway  Havent you changed this on 256 to littlefs?

**Comment by stuartpittaway** [comment]
@daromer2  yes, ESP8266 moved to use LittleFS, although we don't actually use any SPIFF features in 256module branch as its all self compiled into the code.
