### ISSUE TITLE
Rules only allow 65535 input values.

### ISSUE THREAD

**Issue by stuartpittaway** [stuartpittaway/diyBMSv4Code#33]
Found a software limitation “Pack over voltage (mV)” 65500. I have 20 cells 18650 = 84000 mV
When you enter a larger value, it writes what has been saved, when the page is refreshed, it writes other different numbers.

https://community.openenergymonitor.org/t/diybms-v4/11292/2528?u=stuart

**Comment by Daemon256** [comment]
In the new version of the code - it worked correctly

**Comment by stuartpittaway** [comment]
Merged into master
