### ISSUE TITLE
Add hysteresis to relay rules

### ISSUE THREAD

**Issue by karciok** [stuartpittaway/diyBMSv4Code#34]
Hi, 
I have been using your bms for a while and I noticed that when undervoltage or overvoltage events are triggered bms sends signal to turn off load/charging but as soon as device turns off voltage on the cells bounces back a little and bms sends signal to turn on the device. 

It would be great if You could add some sort of hysteresis, so when discharging the cells voltage reaches for example 3V/cell bms sends signal to turn off discharging device, but turning it back on would be possible when cells reach for example 3.2V/cell. Of course overvoltage situation working on the same principle.

It would eliminate constant turning on and off 
of peripheral devices.

**Comment by stuartpittaway** [comment]
Hello, I've written the code for this feature over in a new branch, please take a look!

https://github.com/stuartpittaway/diyBMSv4Code/tree/HysteresisRules

**Comment by Daemon256** [comment]
working!

**Comment by stuartpittaway** [comment]
Hi Daemon256, is it still working as you expect?

**Comment by Daemon256** [comment]
Now I will describe how it actually works (Firmware HysteresisRules, All rules X):
Relay default - OFF -> On the corresponding output, logic 1
Relay default - ON -> On the corresponding output, logic 0

And all the rules work out in exactly the same style. Logically correct to do the opposite.

**Comment by Daemon256** [comment]
For correct work, you need to find the lines in the code:
RELAY_ON ? LOW : HIGH;
And replace them with:
RELAY_ON ? HIGH : LOW;

**Comment by stuartpittaway** [comment]
That only applies to your configuration.  We probably need to add a new option for "inverted" outputs.

**Comment by stuartpittaway** [comment]
Relay rules merged into master branch.
