### ISSUE TITLE
Wifi hostname is not set on controller

### ISSUE THREAD

**Issue by stuartpittaway** [stuartpittaway/diyBMSv4Code#36]
The hostname of the DIYBMS controller should be set to diyBMS_ESP8266 but it is not.

Seems to relate to ESP8266 bug https://github.com/esp8266/Arduino/issues/2826

**Comment by daromer2** [comment]
What about having multiple controllers? I would recommend to either use ESP.getchipid() or use a custom setable unit name. 
Its not the end of the world having same name but good practice to have them different :)

**Comment by stuartpittaway** [comment]
Good idea to use the chipid.  Thanks

**Comment by stuartpittaway** [comment]
Fixed
