### ISSUE TITLE
Mongoose OS

### ISSUE THREAD

**Issue by ZanzyTHEbar** [stuartpittaway/diyBMSv4Code#51]
Feel free to delete this if it's off-topic, however i am wondering if the ESP used in the controller board can have Mongoose OS loaded with the default diybmsv4 code working in tandem. 

My reason, i have the diybms setup and working, and i turned a raspberrypi into an MQTT Broker. I also have a Flask-based Apache webpage that i have turned into a webapp. Currently it uses a 433MHz communication system. I want to reconfigure the webpage/webapp to communicate with the diybms main console. The reason? I have a home automation setup that allows me to control and monitor my home and workspace remotely. I already have the UI and homeautomation setup, i'd simply like to integrate the diybms into the system.

**Comment by stuartpittaway** [comment]
Hello, I've never looked at MongooseOS, so I can't comment if that would work or not - I doubt there is enough RAM/Flash storage for that to work.

The DIYBMS web site uses JSON web messages under the covers, so potentially you could talk to those and get the data that way?
