### ISSUE TITLE
Callibration of voltage only works on cell 0

### ISSUE THREAD

**Issue by daromer2** [stuartpittaway/diyBMSv4Code#57]
Expected: When setting callibration value on cell XX then cell XX should have that callibration voltage setting

Current: If i change on cell 10 still cell 0 is changed and i can see that cell go to NA and then back in the dashboards. 

This is for the 256module branch. I will take a look at hte code later on what could be wrong unless fixed before that and submitt a pull request.

**Comment by stuartpittaway** [comment]
This is a javascript error with the webpage, its not setting the "m" parameter on post.

**Comment by stuartpittaway** [comment]
Ready for retest

**Comment by daromer2** [comment]
It fixed it. Confirmed.
