### ISSUE TITLE
branch 256modules doesnt start up the softap properly but crashes

### ISSUE THREAD

**Issue by daromer2** [stuartpittaway/diyBMSv4Code#60]
When using 256modules branch the softap doesnt work properly. It crashes the ESP after 2 seconds. I tried both the master branch right now that works fine and boots up and start debugging messages properly meanwhile 256 modules look like this:
![image](https://user-images.githubusercontent.com/14975395/101362904-05047380-38a1-11eb-8b8a-b82c7c187390.png)
As can bee seen it crashes and doesnt show the AP.  

Also why is the debugging ofsetted on the 256modules version compare to the master that looks nice?

**Comment by daromer2** [comment]
Workaround is to install master branch and set config then update to 256 without erasing flash

**Comment by donnib** [comment]
@daromer2 great workaround, this was the issue i was mentioning on facebook the other day. Now i am up and running :)

**Comment by daromer2** [comment]
Should fix the issue but i didnt have time to see what differs or why it happens. Have alot to learn about the code first

**Comment by stuartpittaway** [comment]
Change checked in

**Comment by daromer2** [comment]
Works as it should now. Closing.
