### ISSUE TITLE
No Wifi SSID Menu visible

### ISSUE THREAD

**Issue by volkergi** [stuartpittaway/diyBMSv4Code#75]
Hello, with the new Version from December i became no connection to the controllerWemos D1 mini Pro, to set the SSID from the Controller. I only see: 192.168.4.1/softap.htm in the adress field of the browser, with an white screen on different Browser. I have checked it with three different Wemos.

Please help.

**Comment by stuartpittaway** [comment]
Have you programmed the FILE SYSTEM IMAGE ?

See this for help...
https://community.openenergymonitor.org/t/platform-io-v5-upload-file-system-image-option-moved/15492/7
