### ISSUE TITLE
Negative temperatures

### ISSUE THREAD

**Issue by Daemon256** [stuartpittaway/diyBMSv4Code#79]
The balancer stops working at negative temperatures. If you heat the thermister with your finger, work is restored.
https://community.openenergymonitor.org/t/negative-temperatures/16502

**Comment by stuartpittaway** [comment]
In the picture you had a temperature of "-8", was this actually the correct temperature at the module?

**Comment by Daemon256** [comment]
Yes, the temperature is correct, it's -15 outside now, the modules are in the shed, so it's a little warmer.

**Comment by stuartpittaway** [comment]
Hi @Daemon256 , looks like a classic casting variable from int to unsigned int issue.

I've updated the code, if you can test that would be very helpful.

**Comment by Daemon256** [comment]
Now you have to reflash all modules? It will take time.

**Comment by stuartpittaway** [comment]
Just do 1 for now and ensure it starts working again.

**Comment by Daemon256** [comment]
I can check tomorrow

**Comment by Daemon256** [comment]
Confirmed. Works.
