### ISSUE TITLE
Smoke came out of one of the modules

### ISSUE THREAD

**Issue by donnib** [stuartpittaway/diyBMSv4Code#91]
So I started to connect the first modules and suddenly smoke starting coming out of the second module. What may I have done wrong ? Polarity seems correct same does voltage. A bad board ? ![image](https://user-images.githubusercontent.com/252702/106329871-81547b00-6282-11eb-8277-22c659c338ac.jpeg)![image](https://user-images.githubusercontent.com/252702/106329882-84e80200-6282-11eb-98e1-9455e5d742e5.jpeg)

It's LiFePo4 cells, i took the modules on the table at least the two where smoke came from, not sure which one it came from but on the table they work fine with some cells i have laying around. This is very weird. I looked thru the microscope and i can't see anything alarming but then again i didn't leave them after smoke came out so maybe it's half broken or idk.

**Comment by donnib** [comment]
Here are two close-ups of the two modules ![image](https://user-images.githubusercontent.com/252702/106331421-31c37e80-6285-11eb-95d0-cbe925c92429.jpeg)

![image](https://user-images.githubusercontent.com/252702/106331434-3851f600-6285-11eb-8ee4-995b474805dd.jpeg)

**Comment by Chass90** [comment]
Looks like you have connected TX to TX and RX to RX!! I'm surprised you didnt have more than just smoke as this would cause a short between cell 1 and cell 2. Please connect the TX of one module to RX of next module, and so on.

**Comment by donnib** [comment]
![image](https://user-images.githubusercontent.com/252702/106333778-aac4d500-6289-11eb-9132-1050657d53b3.png)
Hmm how can you tell, i didn't see that mistake but i don't know for sure since i removed and placed them again. What's the risk now ?

**Comment by Chass90** [comment]
Your first picture, you have the daisy chain wires going from the bottom right connector of module 1 to the bottom right connector of module 2, then you have the bottom left connector of module 2 going to the bottom left connector of module 3

**Comment by Chass90** [comment]
It should be daisy chained right connector to left of next module and so on.

**Comment by Chass90** [comment]
As for risk, if its working, you are very lucky, but please be careful in future. TX to RX only

**Comment by donnib** [comment]
@Chass90 yes i can see now what you mean, the second module is also wrong, it seems i made a mistake there and as i started putting power on each of them suddenly smoke came out. I was very carreful on the polarity from the battery hence @stuartpittaway warning on the back but i was not aware that swapping TX/RX could brake things badly i mean i am used to RS232 where nothing happens but then it just doesn't work

**Comment by stuartpittaway** [comment]
If you did manage to short out the connections and the board is still working, well done, however I would also check that the JST connections are still okay.  These seem to melt and get loose when heated, and you don't want the cables falling out.

Bizarrely, somebody asked this question only yesterday!
https://community.openenergymonitor.org/t/does-the-polarity-matter-for-the-module-serial-connections/16692

**Comment by donnib** [comment]
@stuartpittaway yes indeed bizarre but even more bizarre is that I read that post since I tend to read what happens but obviously I didn't pay to much attention. I was lucky. I did however disconnected the power as soon as I saw smoke.

**Comment by stuartpittaway** [comment]
I'll update the silk screen to add that warning.  Perhaps the next modules can have a fuse as well :-)

**Comment by donnib** [comment]
That's a good idea !
