### ISSUE TITLE
Wiring the relay board how ?

### ISSUE THREAD

**Issue by donnib** [stuartpittaway/diyBMSv4Code#92]
Hi @stuartpittaway ,
Is there a picture somewhere so i can see how i wire the relay board to the controller ?`

/donnib

**Comment by mihaicph** [comment]
I found your video where i figered out how it was wired. https://www.youtube.com/watch?v=BvyhvHpkdhs&ab_channel=StuartPittaway

**Comment by donnib** [comment]
Found your video https://www.youtube.com/watch?v=BvyhvHpkdhs&ab_channel=StuartPittaway and i figured it out.

**Comment by stuartpittaway** [comment]
The circuit diagram also has the relevant connections
