### ISSUE TITLE
Weird problem on the same spot even after changed the cell

### ISSUE THREAD

**Issue by donnib** [stuartpittaway/diyBMSv4Code#96]
Hi,
I thought i had a bad cell since the voltage went to high on it so i thought the cell is bad so i replaced it and then i had same issue again on the same cell. Now i changed the module. Before i changes i looked at the voltage reading from diybms and the voltmeter and they seemed to be the same so i am puzzled what the problem could be. Any ideas ? 

/donnib

**Comment by stuartpittaway** [comment]
Check the power connections to the module/JST cable and also the cables to the left and right of this module in the chain.

**Comment by donnib** [comment]
@stuartpittaway you mean all the cables to the left and right of the cell or do you mean just the power cables ?

What happened is that this module got to 3.5v (bypass voltage) then the bms tried to keep it down but could not so it got to 3.7v and i stoped the charger entirely since the rule in bms was 3.6v but i only configured the charger to go into float and in float some charging still came in that's why it go to 3.7v. Anyway i disconnected everything then started to burn energy of this cell to get it down to a reasonable level. 

All other cells seems to have balanced fine, bear in mind this is first charge of the pack. Here you can see it's almost there. When done i will connect the charger again but i think before that i will check the cables and maybe measure the voltage to see if there is any calibration needed. If you have other suggestions let me hear.

![image](https://user-images.githubusercontent.com/252702/106940841-55be0e80-6722-11eb-9196-e869c728e4bc.png)

**Comment by fisht99** [comment]
The attached picture shows cell 1 in bypass at 3.35v with a maximum of 3.38v
Is this correct?

**Comment by donnib** [comment]
Yes this is correct. I was trying to balance manually to get the cell down to match the others before i start the charger again. I can't get the voltage up on the pack to 56,8V for Absorption before one cell triggers at 3.6V to stop charging. I don't know what i can do to get it in balance, maybe i need to charge lower ? I am charging at 35A now which is 0,22C.

**Comment by donnib** [comment]
![image](https://user-images.githubusercontent.com/252702/106959301-c53ff800-673a-11eb-9e68-89840a11e77a.png)

**Comment by donnib** [comment]
I have moved around the module and exchanged them around but as soon as i charge the range get's higher and it's always on cell 1 that stops the charger

**Comment by stuartpittaway** [comment]
Drop the current on the charger and trickle charge them until full

**Comment by donnib** [comment]
> Drop the current on the charger and trickle charge them until full

I was just thinking of that. I will try that right now, thx.

**Comment by donnib** [comment]
@stuartpittaway But I think your first comment about the cable is most likely right. I think the power cable for cell two is not crimped well or the contact is bad because I can see it's not capable of bypassing quick enough compared to others. It's always this cell that triggers stop of the charger however trickle charger with lower current seems like the way to go after I solve the cable.

**Comment by donnib** [comment]
![image](https://user-images.githubusercontent.com/252702/106964609-a5accd80-6742-11eb-899b-cac357038874.jpeg)

**Comment by donnib** [comment]
I think trickle charge will fix the problem hopefully.
